on: [push, pull_request]
name: Test
jobs:
  check:
   runs-on: ubuntu-latest
   steps:
   - uses: actions/setup-go@v3
     with:
       go-version: 1.19
   - uses: actions/checkout@v3
   - run: apt-get update
   - run: apt-get -y install make
   - run: make check
  test:
    strategy:
      matrix:
        go-version: [1.19.x]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
    - uses: actions/checkout@v3
    - run: go test -short ./...
